# Generated by Django 2.1 on 2018-08-25 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blogapp', '0003_auto_20180820_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eucation', models.CharField(max_length=120)),
                ('hobbies', models.CharField(max_length=120)),
                ('study', models.CharField(max_length=120)),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='unmarriage', max_length=10)),
                ('marriage', models.CharField(choices=[('single', 'single'), ('marriage', 'marriage')], default='unmarriage', max_length=10)),
                ('photo', models.FileField(upload_to='image/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
