# Generated by Django 2.1 on 2018-08-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='-----', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(upload_to='static/image/'),
        ),
    ]
