# Generated by Django 2.1 on 2018-08-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0008_auto_20180826_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='eucation',
            new_name='education',
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='static/image/'),
        ),
    ]
